apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  ports:


--
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      run: nginx
  template:
    metadata:
      labels:
        run: nginx
    spec:
      containers:
        image: nginx:ssh
        name: nginx
		ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        - containerPort: 4000
          name: ssh
