apiVersion: v1
kind: Service
metadata:
  name: nginx-ssh
spec:
  ports:
    - name: ssh
      protocol: TCP
      port: 30022
      targetPort: 30022
      nodePort: 30022
  selector:
    app: ft_services
    tier: nginx
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP 
      port: 443
      targetPort: 443
  selector:
    app: ft_services
    tier: nginx
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: ft_services
spec:
  selector:
    matchLabels:
      app: ft_services
      tier: nginx
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: ft_services
        tier: nginx
    spec:
      containers:
      - name: nginx
        image: my-nginx
        imagePullPolicy: Never
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        - containerPort: 30022
          name: ssh
        env:
        - name: SSH_USER
          valueFrom:
            secretKeyRef:
              name: ssh
              key: username
        - name: SSH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ssh
              key: password
    