FROM nginx:alpine
RUN apk add --update openssh

# SSH keys created with
# ssh-keygen -t rsa -b 4096 -C "ft_services"
COPY ssh/sshd_config /sshd_config
COPY ssh/id_rsa.pub /authorized_keys
COPY ssh/id_rsa /etc/ssh/ssh_host_rsa_key

# SSL keys created with
# openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
# -subj '/C=FR/ST=75/L=Paris/O=42/CN=name' \
# -keyout nginx.key -out nginx.crt;
COPY ssl/nginx.crt /etc/nginx/ssl/nginx.crt
COPY ssl/nginx.key /etc/nginx/ssl/nginx.key

# nginx setup
COPY nginx.conf /etc/nginx/nginx.conf

# entrypoint
COPY entrypoint /entrypoint

ENTRYPOINT sh /entrypoint

EXPOSE 443 80 30022