#!/bin/sh

# setup SSH
mv -f /sshd_config /etc/ssh/sshd_config
mkdir .ssh
mv /authorized_keys .ssh/authorized_keys
chmod 600 /etc/ssh/ssh_host_rsa_key
chmod 700 .ssh
chmod 644 .ssh/authorized_keys

adduser -D "$SSH_USER"
echo "$SSH_USER:$SSH_PASSWORD" | chpasswd
echo "user:password = $SSH_USER:$SSH_PASSWORD"

# setup SSL
chmod 644 /etc/nginx/ssl/nginx.crt
chmod 600 /etc/nginx/ssl/nginx.key

# run sshd
/usr/sbin/sshd

# run nginx in foreground
/usr/sbin/nginx -g 'daemon off;' 
