#!/bin/sh

MYSQL="mysql -h $WORDPRESS_DB_HOST -u $WORDPRESS_DB_USER --password=$WORDPRESS_DB_PASSWORD"

conn_error()
{
	exit 1
}

# crash if connection error
$MYSQL -e '' || conn_error

# init database

	$MYSQL -e 'CREATE DATABASE wordpress;' ||
		( $MYSQL -e 'DROP DATABASE wordpress;'; conn_error)
	$MYSQL wordpress < /wordpress.sql ||
		( $MYSQL -e 'DROP DATABASE wordpress;'; conn_error)

# setup
sed -i 's/^exec .*//' /usr/local/bin/docker-entrypoint.sh
docker-entrypoint.sh php-fpm

# run
php -S 0.0.0.0:5050 -t /www/
#/usr/sbin/nginx && /usr/local/sbin/php-fpm
